// THIS CODE IS AUTOGENERATED WHEN THE PHP TEST SUITE IS RUN

microlang_test_number = 1;
microlang_test_count = 29;


microlang_tests[1] = function()
{
    var success;

    code = "";

    input = {};

    code = "";

    execute();

    var p,pc = 0;
    for( p in output ) if( output.hasOwnProperty( p ) ) pc++;
    success = assert( pc === 0, '(no data)' );

    return success;
};


microlang_tests[2] = function()
{
    var success;

    code = "";

    input = {};

    code = "   \n\n  \n ";

    execute();

    var p,pc = 0;
    for( p in output ) if( output.hasOwnProperty( p ) ) pc++;
    success = assert( pc === 0, '(no data)' );

    return success;
};


microlang_tests[3] = function()
{
    var success;

    code = "";

    input = { 'a': 1 };

    code = "   \n\n  \n ";

    execute();

    success = assert( output['a'] === 1, 'a = 1' );

    return success;
};


microlang_tests[4] = function()
{
    var success;

    code = "";

    input = { 'a': 'text', 'b': 10, 'c': 12.3 };

    code = "";
    code+= "string ta,tb,tc\n";
    code+= "ta = typeof( a )\n";
    code+= "tb = typeof( b )\n";
    code+= "tc = typeof( c )\n";

    execute();

    success = assert( output['ta'] === 'string' && output['tb'] === 'int' && output['tc'] === 'float', 'ta = "string", tb = "int", tc = "float"' );

    return success;
};


microlang_tests[5] = function()
{
    var success;

    code = "";

    input = { 'a': true, 'b': 1, 'c': 1 }; // boolean not allowed

    code = "";
    code+= "string ta,tb,tc\n";
    code+= "ta = typeof( a )\n";
    code+= "tb = typeof( b )\n";
    code+= "tc = typeof( c )\n";

    execute();

    success = assert();

    return success;
};


microlang_tests[6] = function()
{
    var success;

    code = "";

    input = { 'a': 10 };

    code = "";
    code+= "a = float( a )\n"; // allowed

    execute();

    success = assert( output['a'] === 10.0, 'a = 10.0' );

    return success;
};


microlang_tests[7] = function()
{
    var success;

    code = "";

    input = { 'a': 12.3 };

    code = "";
    code+= "a = int( a )\n"; // not allowed

    execute();

    success = assert();

    return success;
};


microlang_tests[8] = function()
{
    var success;

    code = "";

    input = { 'a': 1 };

    code = "";
    code+= "string b";
    code+= "b = \"foo\"\n";
    code+= "a = b\n"; // type change not allowed

    execute();

    success = assert();

    return success;
};


microlang_tests[9] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "int    stoi,itoi,ftoi\n";
    code+= "float  stof,itof,ftof\n";
    code+= "string stos,itos,ftos\n";
    code += "\n";
    code+= "string s = \"10.8\"\n";
    code+= "stoi = int(    s )\n";
    code+= "stof = float(  s )\n";
    code+= "stos = string( s )\n";
    code+= "\n";
    code+= "int i = 10E2\n";
    code+= "itoi = int(    i )\n";
    code+= "itof = float(  i )\n";
    code+= "itos = string( i )\n";
    code+= "\n";
    code+= "float f = 10.0e-2\n";
    code+= "ftoi = int(    f )\n";
    code+= "ftof = float(  f )\n";
    code+= "ftos = string( f )\n";

    execute();

    success = assert( output['stoi'] === 10 && output['stof'] === 10.8 && output['stos'] === "10.8" && output['itoi'] === 1000 && output['itof'] === 1000.0 && output['itos'] === "1000" && output['ftoi'] === 0 && output['ftof'] === 0.1 && output['ftos'] === "0.1", 'stoi = 10, stof = 10.8, stos = "10.8", itoi = 1000, itof = 1000.0, itos = "1000", ftoi = 0, ftof = 0.1, ftos = "0.1"' );

    return success;
};


microlang_tests[10] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "int i\n";
    code+= "string ti\n";
    code+= "i = -10e2\n";
    code+= "ti= typeof( i )\n";
    code+= "\n";
    code+= "float f\n";
    code+= "string tf\n";
    code+= "f = .0\n";
    code+= "tf= typeof( f )\n";

    execute();

    success = assert( output['i'] === -1000 && output['ti'] === 'int' && output['f'] === 0.0 && output['tf'] === 'float', 'i = -1000, ti = "int", f = 0.0, tf = "float"' );

    return success;
};


microlang_tests[11] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "int a,b\n";
    code+= "a = 10\n";
    code+= "b = 1\n";
    code+= "loop:\n";
    code+= "  if b > 20 then finish\n";
    code+= "  a = a + a\n";
    code+= "  b = b + 1\n";
    code+= "goto loop\n";
    code+= "\n";
    code+= "finish:\n";
    code+= "exit\n";

    execute();

    success = assert( output['a'] === 10485760, 'a = 10485760' );

    return success;
};


microlang_tests[12] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string a = \"xxxxxxxxxx\"\n";
    code+= "int b = 1\n";
    code+= "loop:\n";
    code+= "  if b > 20 then finish\n";
    code+= "  a = a + a\n";
    code+= "  b = b + 1\n";
    code+= "goto loop\n";
    code+= "\n";
    code+= "finish:\n";
    code+= "exit\n";

    execute();

    success = assert();

    return success;
};


microlang_tests[13] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "int a = 10\n";
    code+= "int b = 1\n";
    code+= "loop:\n";
    code+= "  if b > 100 then finish\n";
    code+= "  a = a + a\n";
    code+= "  b = b + 1\n";
    code+= "goto loop\n";
    code+= "\n";
    code+= "finish:\n";
    code+= "exit\n";

    execute();

    success = assert();

    return success;
};


microlang_tests[14] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "int a = -10\n";
    code+= "int b = 1\n";
    code+= "loop:\n";
    code+= "  if b > 100 then finish\n";
    code+= "  a = a + a\n";
    code+= "  b = b + 1\n";
    code+= "goto loop\n";
    code+= "\n";
    code+= "finish:\n";
    code+= "exit\n";

    execute();

    success = assert();

    return success;
};


microlang_tests[15] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( \"\\t\\t\\r  \\n \\n foo \\n\\n  \\n\" )";

    execute();

    success = assert( output['s'] === 'foo', 's = "foo"' );

    return success;
};


microlang_tests[16] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( \"  \\n \\n foo bar\\n\\n  \\n\" )\n";

    execute();

    success = assert( output['s'] === 'foo bar', 's = "foo bar"' );

    return success;
};


microlang_tests[17] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( \"foo bar\" )";

    execute();

    success = assert( output['s'] === 'foo bar', 's = "foo bar"' );

    return success;
};


microlang_tests[18] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( \"\" )";

    execute();

    success = assert( output['s'] === '', 's = ""' );

    return success;
};


microlang_tests[19] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( 100 )";

    execute();

    success = assert();

    return success;
};


microlang_tests[20] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = trim( \"\" )";

    execute();

    success = assert( output['s'] === '', 's = ""' );

    return success;
};


microlang_tests[21] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 0, 4 )";

    execute();

    success = assert( output['s'] === 'some', 's = "some"' );

    return success;
};


microlang_tests[22] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 5, 4 )";

    execute();

    success = assert( output['s'] === 'text', 's = "text"' );

    return success;
};


microlang_tests[23] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 5, 1000 )";

    execute();

    success = assert( output['s'] === 'text', 's = "text"' );

    return success;
};


microlang_tests[24] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 20, 30 )";

    execute();

    success = assert( output['s'] === '', 's = ""' );

    return success;
};


microlang_tests[25] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", -4, 4 )";

    execute();

    success = assert( output['s'] === 'text', 's = "text"' );

    return success;
};


microlang_tests[26] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 5, -2 )";

    execute();

    success = assert( output['s'] === 'te');

    return success;
};


microlang_tests[27] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( 100, 0, 1 )";

    execute();

    success = assert();

    return success;
};


microlang_tests[28] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", \"0\", 4 )";

    execute();

    success = assert();

    return success;
};


microlang_tests[29] = function()
{
    var success;

    code = "";

    input = {};

    code = "";
    code+= "string s\n";
    code+= "s = substring( \"some text\", 0, \"4\" )";

    execute();

    success = assert();

    return success;
};


